server:
  port: 8181

spring:
  application:
    name: service-login
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    user:
      name: admin
      password: admin
      roles:
        - admin
#  main:
#    allow-bean-definition-overriding: true